import { AppShell } from "@/ui/components/app-shell";
import { InsightsPage } from "@/ui/sections/insights-page";

export const metadata = {
  title: "Insights Feed | MarketIQ",
  description: "Real-time financial intelligence feed generated by AI."
};

export default function Page() {
  return (
    <AppShell activePath="/insights">
      <InsightsPage />
    </AppShell>
  );
}
